
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geehtlhvuprdggksktnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZWh0bGh2dXByZGdna3NrdG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTY4MTksImV4cCI6MjA1OTMzMjgxOX0.PuU_6fVy1IVt0i7eo6PXbEWVV0asgCJuvyKl3VDuN8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
